FROM mcr.microsoft.com/dotnet/sdk:9.0.202

RUN apt-get update \
    && apt-get install --no-install-recommends -y clang zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /project
WORKDIR /project

ENTRYPOINT ["./build.sh"]
